export const AVAILABLE_SKILLS = [
  "3d-web-experience", "academy-guide", "agent-md-refactor", "agentcad", "agy-customizations",
  "ai-ml", "ai-product-development", "algorithmic-art", "antigravity-guide", "backend-to-frontend-handoff-docs",
  "bambu-labs", "blender-agent-studio", "brand-guidelines", "c4-architecture", "cad",
  "cad-viewer", "canvas-design", "claude-api", "codex", "command-creator",
  "commit-work", "composio", "crafting-effective-readmes", "daily-meeting-update", "data-analyst",
  "database-schema-designer", "datadog-cli", "dependency-updater", "design-system-starter", "dfam-check",
  "difficult-workplace-conversations", "discernment-nudge", "doc-coauthoring", "docx", "domain-name-brainstormer",
  "draw-io", "dxf", "excalidraw", "feedback-mastery", "frontend-design",
  "frontend-to-backend-requirements", "game-changing-features", "gcode", "gemini", "gepetto",
  "humanizer", "implicit-cad", "internal-comms", "jira", "lesson-learned",
  "marp-slide", "mcp-builder", "meme-factory", "mermaid-diagrams", "mui",
  "naming-analyzer", "openapi-to-typescript", "pdf", "perplexity", "plugin-forge",
  "pptx", "professional-communication", "qa-test-planner", "react-dev", "react-useeffect",
  "reducing-entropy", "requirements-clarity", "sdf", "sendcutsend", "session-handoff",
  "ship-learn-next", "skill-creator", "skill-judge", "slack-gif-creator", "srdf",
  "step-parts", "template-skill", "theme-factory", "threejs-atmosphere-aerial-perspective", "threejs-bloom",
  "threejs-camera-direction", "threejs-exposure-color-grading", "threejs-image-pipeline", "threejs-parallax-occlusion-mapping", "threejs-precipitation-surfaces",
  "threejs-procedural-animation", "threejs-procedural-architecture", "threejs-procedural-fields", "threejs-procedural-geometry", "threejs-procedural-materials",
  "threejs-procedural-planets", "threejs-procedural-vegetation", "threejs-procedural-vfx", "threejs-raymarched-space-effects", "threejs-screen-space-ambient-occlusion",
  "threejs-shadow-systems", "threejs-skill-router", "threejs-spectral-ocean", "threejs-temporal-surfaces", "threejs-visual-validation",
  "threejs-volumetric-clouds", "threejs-water-optics", "urdf", "web-artifacts-builder", "web-to-markdown",
  "webapp-testing", "writing-clearly-and-concisely", "xlsx"
];
